import { z } from 'zod'

export const movieSchema = z.object({
  title: z.string().min(1),
  year: z.number().int().min(1900).max(2100),
  genres: z.array(z.string().min(1)),
  directors: z.array(z.string().min(1)),
  writers: z.array(z.string().min(1)),
  posterUrl: z.string().url(),
  type: z.enum(['movie', 'series']),
  plot: z.string().min(1),
  actors: z.array(z.string().min(1)),
})

type Movie = z.infer<typeof movieSchema> & { id: number }

export const movies: Array<Movie> = [
  {
    id: 1,
    title: 'The Shawshank Redemption',
    year: 1994,
    genres: ['Drama'],
    directors: ['Frank Darabont'],
    writers: ['Stephen King', 'Frank Darabont'],
    posterUrl: 'https://www.example.com/shawshank_redemption.jpg',
    type: 'movie',
    plot: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    actors: ['Tim Robbins', 'Morgan Freeman'],
  },
  {
    id: 2,
    title: 'The Godfather',
    year: 1972,
    genres: ['Crime', 'Drama'],
    directors: ['Francis Ford Coppola'],
    writers: ['Mario Puzo', 'Francis Ford Coppola'],
    posterUrl: 'https://www.example.com/the_godfather.jpg',
    type: 'movie',
    plot: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    actors: ['Marlon Brando', 'Al Pacino'],
  },
  {
    id: 3,
    title: 'Pulp Fiction',
    year: 1994,
    genres: ['Crime', 'Drama'],
    directors: ['Quentin Tarantino'],
    writers: ['Quentin Tarantino', 'Roger Avary'],
    posterUrl: 'https://www.example.com/pulp_fiction.jpg',
    type: 'movie',
    plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    actors: ['John Travolta', 'Samuel L. Jackson'],
  },
  {
    id: 4,
    title: 'Breaking Bad',
    year: 2008,
    genres: ['Crime', 'Drama', 'Thriller'],
    directors: ['Vince Gilligan'],
    writers: ['Vince Gilligan'],
    posterUrl: 'https://www.example.com/breaking_bad.jpg',
    type: 'series',
    plot: 'A high school chemistry teacher turned methamphetamine manufacturer partners with a former student to secure his family\'s financial future as he battles terminal lung cancer.',
    actors: ['Bryan Cranston', 'Aaron Paul'],
  },
  {
    id: 5,
    title: 'Stranger Things',
    year: 2016,
    genres: ['Drama', 'Fantasy', 'Horror'],
    directors: ['The Duffer Brothers'],
    writers: ['The Duffer Brothers'],
    posterUrl: 'https://www.example.com/stranger_things.jpg',
    type: 'series',
    plot: 'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.',
    actors: ['Millie Bobby Brown', 'Finn Wolfhard'],
  },
]
